### ISSUE TITLE
Error when starting Pushion Passenger

### ISSUE THREAD

**Issue by skyporter** [translation/rails#52]
With the last version of this gem (1.33), on rails 6.1.7, ruby 2.7.5, nginx 1.20.2, passenger can't start the web server.

Here are the details of the error found in `/var/log/nginx/error.log`:
```
App 23240 output: Error: The application encountered the following error: You have already activated forwardable 1.3.1, but your Gemfile requires forwardable 1.3.2. Since forwardable is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports forwardable as a default gem. (Gem::LoadError)
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/runtime.rb:309:in `check_for_activated_spec!'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/runtime.rb:25:in `block in setup'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/spec_set.rb:136:in `each'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/spec_set.rb:136:in `each'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/runtime.rb:24:in `map'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/runtime.rb:24:in `setup'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler.rb:151:in `setup'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/setup.rb:20:in `block in <top (required)>'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/ui/shell.rb:136:in `with_level'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/ui/shell.rb:88:in `silence'
App 23240 output:     /usr/local/rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/setup.rb:20:in `<top (required)>'
App 23240 output:     /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
App 23240 output:     /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `activate_gem'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:544:in `running_bundler'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/helper-scripts/rack-preloader.rb:91:in `preload_app'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 23240 output:     /usr/local/rvm/gems/current-gems/gems/passenger-version/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-11-11 23:11:53.9649 13906/T4q age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/webroot/ROOT: The application encountered the following error: You have already activated forwardable 1.3.1, but your Gemfile requires forwardable 1.3.2. Since forwardable is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports forwardable as a default gem. (Gem::LoadError)
  Error ID: 90d7c365
  Error details saved to: /tmp/passenger-error-YXams6.html
  ```

` forwardable` seems to be a dependence of `gettext` so I'm uncertain if your gem is responsible for that (please note that I don't 
 use the `gettext` gem, so parameter ` config.disable_gettext` is set to `true`).

**Comment by MichaelHoste** [comment]
This is actually a Passenger issue that can be solved with this server configuration:

`passenger_env_var RUBYOPT '-r bundler/setup';`

Please see this thread: https://github.com/phusion/passenger/issues/2409#issuecomment-1009548218

Version 6.0.13 of Passenger seems to have added [a new option](https://github.com/phusion/passenger/blob/stable-6.0/CHANGELOG) with the same effect:

   - Apache: PassengerPreloadBundler
   - Nginx: passenger_preload_bundler
   - Standalone: --preload_bundler

**Comment by skyporter** [comment]
Thank you, @MichaelHoste, now it's works fine!
